version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: helpmeplz
      # MONGO_INITDB_ROOT_PASSWORD: public_static_void_main_string_args
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: public
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  app:
    build: .
    restart: always
    ports:
      - '555:555'
    depends_on:
      - db
volumes:
  mongo-data: